spring:
  redis:
    host: 119.45.56.227
    port: 6379

  datasource:
    url: jdbc:mysql://119.45.56.227:3306/common_mistakes?characterEncoding=UTF-8&useSSL=false&rewriteBatchedStatements=true
    username: root
    password: 123456
    platform: mysql
    driver-class-name: com.mysql.cj.jdbc.Driver
#    hikari:
#      maximum-pool-size: 100
#      register-mbeans: true




  jpa:
    hibernate:
      ddl-auto: 'create-drop'
